name: 'Docker Pull and Run Tests'
description: 'Pulls a Docker image, runs tests and save it as test output'
inputs:
  script-path:
    description: 'Path to the script to be executed'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Tests
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          ./docker-action/run-tests.sh
        elif [ "$RUNNER_OS" == "Windows" ]; then
          ./docker-action/run-tests.bat
        else
          echo "Unsupported operating system: $RUNNER_OS"
          exit 1
        fi
      shell: bash
