name: Docker Pull image from Github Packages, Run Tests on it and Upload test results as Artifacts to Github.

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pull-run-test-and-upload-artifacts:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Execute Permission for run-tests.sh
        if: runner.os == 'macOS'
        run: chmod +x docker-action/run-tests.sh

      - name: Docker Pull and Run Tests
        uses: ./docker-action
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}

      - name: Upload Test Output
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: test_output.txt
