name: Docker Pull image from Github Packages, Run Tests on it and Upload test results as Artifacts to Github.

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  pull-run-test-and-upload-artifacts:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image
        run: docker pull ghcr.io/bsarahle/cbd3345_ica2/python-app:latest

      - name: Run Docker Container with Tests
        run: |
          # Run tests and save output
          docker run --rm ghcr.io/bsarahle/cbd3345_ica2/python-app:latest python -m unittest test_app.py > test_output.txt 2>&1

      - name: Upload Test Output
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test_output.txt
