name: Docker Pull image from Github Packages, Run Tests on it and Upload test results as Artifacts to Github.

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pull-run-test-and-upload-artifacts:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image
        run: docker pull ghcr.io/bsarahle/cbd3345_ica2/python-app:latest

      - name: Run Docker Container with Tests
        run: |
          # Create a subdirectory for test output
          mkdir -p $GITHUB_WORKSPACE/test_output

          # Run tests and save output in the subdirectory
          docker run --rm ghcr.io/bsarahle/cbd3345_ica2/python-app:latest python -m unittest test_app.py > $GITHUB_WORKSPACE/test_output/test_output.txt
          cat $GITHUB_WORKSPACE/test_output/test_output.txt

          # Zip the entire subdirectory using tar
          tar -cf $GITHUB_WORKSPACE/test_output.tar -C $GITHUB_WORKSPACE test_output

          # Copy the zipped file to ~/Desktop/actions-runner/
          cp $GITHUB_WORKSPACE/test_output.tar ~/Desktop/actions-runner/

      - name: Upload Test Output
        uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: $GITHUB_WORKSPACE
