name: Build and Deploy Docker Image

on:
  push:
    branches:
      - custom-action

jobs:
  build-and-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        runner-label: [mac] # Specify the label for macOS ARM runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute build and deploy script
        run: bash docker_build.sh
