name: Docker Pull and Run

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pull-and-run-docker:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image
        run: docker pull ghcr.io/bsarahle/cbd3345_ica2/python-app:latest

      - name: Run Docker Image
        run: docker run ghcr.io/bsarahle/cbd3345_ica2/python-app:latest

      # Add additional steps as needed
