
# GitHub Actions workflow for running unit tests on the application and storing the test reports as an artifact
name: Python Unit Tests

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust this based on your project setup

    - name: Run tests
      run: |
        python -m unittest test_app.py > ./test-reports/test_output.txt 2>&1

    - name: Archive test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test-reports
