
# GitHub Actions workflow for running unit tests on the application and storing the test reports as an artifact
name: Python Unit Tests

on:
  push:
    branches:
      - bsarahle-patch-3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and log results
        run: |
          python -m unittest test_app.py > test_results.txt
          cat test_results.txt
          python parse_test_results.py test_results.txt

      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: test_results.txt

