
# GitHub Actions workflow for running unit tests on the application and storing the test reports as an artifact
name: Python Unit Tests

on:
  push:
    branches:
      - bsarahle-patch-3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Run tests
        run: |
         pip install pytest pytest-cov
         pytest test_app.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
         
      - name: Archive test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: test-reports

