
# GitHub Actions workflow for running unit tests on the application and storing the test reports as an artifact
name: Python Unit Tests

on:
  push:
    branches:
      - bsarahle-patch-3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest tests_app.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
         
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            junit/test-results.xml
            coverage.xml
            htmlcov/

